In [1]:
import torch

In [2]:
import torch

# Create a tensor with values 0-11 and reshape it into a 3x4 matrix
matrix = torch.arange(12).reshape(3, 4)
print(matrix)

# Convert to a numpy array and check the shape
print(matrix.numpy(), '\n')
print(matrix.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

torch.Size([3, 4])


In [3]:
# Add a scalar to the matrix (Broadcasting)
# This adds 2 to every element in the tensor
matrix2 = matrix + 2
print(matrix2)

# Element-wise addition of two matrices
print(matrix + matrix2)

tensor([[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]])
tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]])


In [4]:
# relu
def my_relu(x):
    zero = torch.zeros(x.shape)
    return torch.maximum(zero, x)

# sigmoid
def my_sigmoid(x):
    return 1 / (1 + torch.exp(-x))

# softmax
def my_softmax(x):
    expo = torch.exp(x)
    expo_sum = torch.sum(expo)
    return expo / expo_sum

# softplus
def my_softplus(x):
    return torch.log(torch.exp(x) + 1.0)

In [5]:
# mean squared error
def mse(y_true, y_pred):
    error = y_true - y_pred
    square = torch.square(error)
    square = square.type(torch.FloatTensor)
    return torch.mean(square)

In [6]:
# OOP approach required if function has a hyper parameter
class MyHuberLoss(torch.nn.Module):
    def __init__(self, threshold=1.0):
        self.threshold = threshold
        super().__init__()

    def __call__(self, y_true, y_pred):
        error = y_true - y_pred
        is_small_error = torch.abs(error) < self.threshold
        squared_loss = torch.square(error) / 2
        linear_loss = self.threshold * torch.abs(error) - self.threshold**2 / 2
        return torch.where(is_small_error, squared_loss, linear_loss)

In [7]:
# Functional Programming approach
def my_l1_regularizer(weight, factor = 0.01):
    return torch.sum(torch.abs(factor * weight))

def my_l2_regularizer(weight, factor = 0.01):
    return torch.sum(torch.square(factor * weight))

In [8]:
# OOP approach
class MyL1Regularizer(torch.nn.Module):
    def __init__(self, factor = 0.01):
        super().__init__()
        self.factor = factor

    def __call__(self, weight):
        return torch.sum(torch.abs(self.factor * weight))

In [9]:
class MyLinear(torch.nn.Module):
    def __init__(self, units, activation=None):
        super().__init__()
        # units is expected to be a tuple/list: (input_dim, output_dim)
        self.input_size, self.output_size = units[0], units[1]

        # Initialize weights randomly and bias with zeros
        self.weight = torch.rand(size=(self.input_size, self.output_size))
        self.bias = torch.zeros(size=(self.output_size,))

        if activation == None:
            self.activation = lambda x: x
        else:
            self.activation = activation

    def __call__(self, x):
        # Flatten input to match weight dimensions if necessary
        # Matrix Multiplication: X @ W + b
        y = torch.matmul(x.reshape((-1, self.weight.shape[0])), self.weight) + self.bias

        # Apply activation and reshape output
        return self.activation(y).reshape(-1, )