In [2]:
import numpy as np

# create rank 1 dim array
arr = np.array([1, 2, 3])
print(type(arr))         # outputs <class 'numpy.ndarray'>
print(arr.dtype)         # outputs int64
print(arr.shape)         # outputs (3,)
print(arr[0], arr[1], arr[2])  # outputs 1 2 3
arr[2] = 4              # change last element to 4
print(arr)              # outputs [1 2 4]

<class 'numpy.ndarray'>
int64
(3,)
1 2 3
[1 2 4]


In [3]:
# create rank 2 array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)       # outputs (2, 3)
print(arr2[0, 0], arr2[0, 1], arr2[1, 0])  # outputs 1 2 4
print(arr2[-1])         # outputs last element [4 5 6]

(2, 3)
1 2 4
[4 5 6]


In [4]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2,2))
print(zero)             # outputs "[[0. 0.]
                        #           [0. 0.]]"

# create an array of ones with 1 dim and size of 2 each
one = np.ones((1,2))
print(one)              # outputs "[[1. 1.]]"

# create a new array with given shape, type, and filled with value
constant = np.full((2,2), 5)  # default type is float
print(constant)         # outputs "[[5 5]
                        #           [5 5]]"

# create a 2-D array with 1 on diagonal and 0 on others
diag = np.eye(3)        # number of rows
print(diag)             # outputs "[[1. 0. 0.]
                        #           [0. 1. 0.]
                        #           [0. 0. 1.]]"

# diag starts at index 1
diag = np.eye(4, k=1)
print(diag)             # outputs "[[0. 1. 0. 0.]
                        #           [0. 0. 1. 0.]
                        #           [0. 0. 0. 1.]
                        #           [0. 0. 0. 0.]]"

# Create an array with random values
rand = np.random.random((2,2))
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[5 5]
 [5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0.40914783 0.29169733]
 [0.61154418 0.15493697]]


In [5]:
# Array indexing

arr = np.arange(10)  # generate array [0 1 2 3 4 5 6 7 8 9]
print(arr[0:8:2])    # every two numbers from 0 up to but not including 8

# create rank 2 with shape (3, 4) array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])
print(arr[:2, :2])   # outputs [[1 2]
                     #          [5 6]]

[0 2 4 6]
[[1 2]
 [5 6]]


In [6]:
# Integer indexing

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 1]])  # outputs [1 4 6]

# arr[[0, 1, 2], [0, 1, 1]] is equivalent to [arr[0, 0], arr[1, 1], arr[2, 1]]

[1 4 6]
